[package]
edition.workspace = true
name = "libraw-sys"
version.workspace = true

[build-dependencies]
bindgen = { workspace = true, option = true }
clerk = { workspace = true, features = ["log"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies]
libc = { workspace = true }

[features]
bindgen = []
