[package]
edition.workspace = true
name = "libraw-sys"
version.workspace = true

[build-dependencies]
bindgen = { workspace = true, option = true }

[dependencies]
libc = { workspace = true }

[features]
bindgen = []