[package]
edition.workspace = true
name = "libraw-sys"
version.workspace = true

[dependencies]
libc = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
dunce = { workspace = true }
pkg-config = { workspace = true }
