[package]
edition.workspace = true
name = "libraw-sys"
version.workspace = true

[build-dependencies]
vcpkg = {workspace=true}
cc =  {workspace=true}
cxx-build =  {workspace=true}
bindgen={workspace=true}
[dependencies]
libc =  {workspace=true}
cxx = {workspace=true}
