[package]
edition.workspace = true
name = "dng-converter"
version.workspace = true

[dependencies]
fornax-core = { workspace = true }
libraw = { workspace = true }
miette = { workspace = true }
libraw-sys = { workspace = true }