package:
  version: 0.0.2
  name: fornax-py
build:
  number: 1
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-fornax-py.ps1

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python >= 3.11
    - lazy-loader
    - numpy
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax
