package:
  version: 0.0.10
  name: fornax-py
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-fornax-py.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-fornax-py.ps1

requirements:
  host:
    - python 3.13.*
    - pip
  run:
    - python >= 3.13
    - lazy-loader
    - pydantic
    - msgspec

tests:
  - python:
      imports:
        - fornax
