version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - .github/workflows
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    groups:
      dependencies:
        patterns:
          - "*"
