[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.21.3"

[workspace.dependencies]
bindgen = "0.71"
clerk = { git = "https://github.com/Glatzel/clerk", tag = "v0.0.5" }
libc = "0.2"
miette ={version= "7.5.0",features=["fancy"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
validator = { version = "0.20.0", features = ["derive"] }
image = "0.25.5"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true

[profile.develop]
inherits = "dev"
