[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.7"

[workspace.dependencies]
dnc = { path = "./crates/dnc" }
fornax = { path = "./crates/fornax" }
fornax-core = { path = "./crates/fornax-core" }
fornax-dalim = { path = "./crates/fornax-dalim" }
fornax-devtool = { path = "./crates/fornax-devtool" }
libraw = { path = "./crates/libraw" }
libraw-sys = { path = "./crates/libraw-sys" }

assert_cmd = "2.0"
bindgen = "0.71.1"
bytemuck = "1.23.1"
chrono = "0.4.40"
clerk = { git = "https://github.com/Glatzel/clerk", tag = "v0.0.20" }
dunce = "1.0.5"
envoy = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.20" }
# image = "0.25.5"
float-cmp = "0.10.0"
image = { git = "https://github.com/fintelia/image", branch = "primitive-ext" }
libc = "0.2"
miette = { version = "7.5.0", features = ["fancy"] }
num_enum = "0.7.3"
numpy = "0.25.0"
path-slash = "0.2.1"
pkg-config = "0.3.32"
pyo3 = { version = "0.25.1", features = ["extension-module", "abi3-py311"] }
rayon = "1.10.0"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true

[profile.develop]
inherits = "dev"
