[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.2"

[workspace.dependencies]
dnc = { path = "./crates/dnc" }
fornax = { path = "./crates/fornax" }
fornax-core = { path = "./crates/fornax-core" }
libraw = { path = "./crates/libraw" }
libraw-sys = { path = "./crates/libraw-sys" }

assert_cmd = "2.0"
bindgen = "0.71"
bytemuck = "1.22.0"
chrono = "0.4.40"
clerk = { git = "https://github.com/Glatzel/clerk", tag = "v0.0.5" }
dunce = "1.0.5"
image = "0.25.5"
libc = "0.2"
miette = { version = "7.5.0", features = ["fancy"] }
path-slash = "0.2.1"
pyo3 = { version = "0.24.1", features = ["extension-module", "abi3-py311"] }
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
numpy = "0.24.0"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true

[profile.develop]
inherits = "dev"
