[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.1"

[workspace.dependencies]
assert_cmd = "2.0"
bindgen = "0.71"
bytemuck = "1.22.0"
chrono = "0.4.40"
clerk = { git = "https://github.com/Glatzel/clerk", tag = "v0.0.5" }
fornax = { path = "./crates/fornax" }
image = "0.25.5"
libc = "0.2"
miette = { version = "7.5.0", features = ["fancy"] }
numpy = "0.23.0"
pyo3 = { version = "0.23.4", features = ["extension-module", "abi3-py311"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true

[profile.develop]
inherits = "dev"
