[package]
edition.workspace = true
name = "dnc"
version.workspace = true

[dependencies]
clerk = { workspace = true }
fornax-core = { workspace = true }
libraw = { workspace = true }
libraw-sys = { workspace = true }
miette = { workspace = true }
path-slash = { workspace = true }
serde = { workspace = true, optional = true }
dunce = { workspace = true }

[features]
log = ["clerk/log"]
serde = ["dep:serde"]
