[package]
edition.workspace = true
name = "dnc"
version.workspace = true

[dependencies]
clerk = { workspace = true }
dunce = { workspace = true }
miette = { workspace = true }
path-slash = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
assert_cmd = { workspace = true }
clerk = { workspace = true, features = ["log"] }
dunce = { workspace = true }
path-slash = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
log = ["clerk/log"]
serde = ["dep:serde"]
