[package]
edition.workspace = true
name = "libraw"
version.workspace = true

[dependencies]
libraw-sys = { path = "../libraw-sys" }
libc= { workspace = true}
[features]
bindgen = ["libraw-sys/bindgen"] 