[package]
edition.workspace = true
name = "libraw"
version.workspace = true

[dependencies]
bytemuck = { workspace = true}
chrono = { workspace = true }
clerk = { workspace = true }
fornax-traits = { workspace = true }
image = { workspace = true }
libraw-sys = { path = "../libraw-sys" }
miette = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
assert_cmd = "2.0"
clerk = { workspace = true, features = ["log"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
log = ["clerk/log"]
serde = ["dep:serde", "chrono/serde"]
