[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
fornax-core = { workspace = true }
miette = { workspace = true }
libraw = { workspace = true }
dnc = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["log"] }
dunce = { workspace = true }
path-slash = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
assert_cmd= { workspace = true }

[features]
log=["clerk/log"]
serde=["libraw/serde","dnc/serde"]