[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
bytemuck = { workspace = true, optional = true }
chrono = { workspace = true }
clerk = { workspace = true }
image = { workspace = true, optional = true }
libraw-sys = { path = "../libraw-sys" }
miette = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
assert_cmd = "2.0"
clerk = { workspace = true, features = ["log"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["image"]
image = ["dep:image", "dep:bytemuck"]
log = ["clerk/log"]
serde = ["dep:serde", "chrono/serde"]
