[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
libraw-sys = { path = "../libraw-sys" }
libc= { workspace = true}
validator = { workspace = true}

[features]
bindgen = ["libraw-sys/bindgen"] 