[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
libraw-sys = { path = "../libraw-sys" }
libc = { workspace = true }
validator = { workspace = true }
serde = { workspace = true, optional = true }

[features]
bindgen = ["libraw-sys/bindgen"]
serde = ["dep:serde"]
