[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
clerk = { workspace = true }
libc = { workspace = true }
libraw-sys = { path = "../libraw-sys" }
miette = { workspace = true }
serde = { workspace = true, optional = true }
validator = { workspace = true }

[features]
log = ["clerk/log"]
serde = ["dep:serde"]
