[package]
edition.workspace = true
name = "fornax"
version.workspace = true

[dependencies]
fornax-traits = { workspace = true }
image = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["log"] }
libraw = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
