[package]
edition.workspace = true
name = "fornax-py"
version.workspace = true

[dependencies]
fornax = { workspace = true, features = ["serde"] }
pyo3 = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }

[lib]
crate-type = ["cdylib"]
name = "fornax_py"
