name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  cargo-doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: ./.github/actions/rust/setup-rust
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{github.event_name=='pull_request'}}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          run-install: false
      - uses: ./.github/actions/rust/cargo-doc

  test-build:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    env:
      dnc_version: 18_0
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: restore dnc
        if: ${{runner.os != 'Linux'}}
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ./temp/dnc${{env.dnc_version}}*
          key: dnc-${{ runner.os }}-${{env.dnc_version}}
      - if: ${{runner.os != 'Linux'}}
        run: ./scripts/install-dnc.ps1 -version ${{env.dnc_version}}
        shell: pwsh
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - if: ${{matrix.machine=='ubuntu-latest'}}
        uses: ./.github/actions/rust/cargo-clippy
      - uses: ./.github/actions/rust/cargo-test
        with:
          global-args: --workspace --all-features --exclude fornax-py
      - name: build
        run: |
          ./scripts/maturin-develop.ps1
        shell: pwsh
      - uses: ./.github/actions/python/pytest
        with:
          working-directory: ./crates/fornax-py
      - uses: ./.github/actions/common/codecov
        if: ${{ !cancelled() }}
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, cargo-doc, test-build]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
