name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
  cargo-doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{github.event_name=='pull_request'}}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
      - uses: ./.github/actions/rust/cargo-doc

  test-build:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    env:
      dnc_version: 18_0
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: restore dnc
        if: ${{runner.os != 'Linux'}}
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ./temp/dnc${{env.dnc_version}}*
          key: dnc-${{ runner.os }}-${{env.dnc_version}}
      - if: ${{runner.os != 'Linux'}}
        run: ./scripts/install-dnc.ps1 -version ${{env.dnc_version}}
        shell: pwsh
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - if: ${{matrix.machine=='ubuntu-latest'}}
        uses: ./.github/actions/rust/cargo-clippy
      - uses: ./.github/actions/rust/cargo-test
        with:
          args: --workspace --all-features --exclude fornax-py
      - name: pytest
        run: |
          ./scripts/maturin-develop.ps1
          ./scripts/pytest.ps1
        shell: pwsh

      - name: Upload results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          report_type: test_results
          fail_ci_if_error: true
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, cargo-doc, test-build]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
