name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml

  python:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-24.04-arm]

    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@stable
      - name: pytest
        run: |
          ./scripts/maturin-develop.ps1
          ./scripts/pytest.ps1
        shell: pwsh
      - name: Upload results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          fail_ci_if_error: true
  rust:
    uses: ./.github/workflows/rust.yml
    with:
      working-directory: "./rust"
      setup-pixi: true
      clippy: true
      doc: true
      test: true
      test-machine: "['windows-latest', 'ubuntu-latest', 'macos-latest', 'ubuntu-24.04-arm']"

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, python, rust]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
