name: libraw-bindgen
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  libraw-bindings:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: windows-latest
            os: win
          - machine: ubuntu-latest
            os: linux
          - machine: macos-latest
            os: macos
          - machine: ubuntu-26.04-arm
            os: linux-aarch64
    runs-on: ${{matrix.machine}}
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - parallel:
          - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
            with:
              run-install: false
          - uses: ./.github/actions/rust/setup-rust
      - name: libraw-bindings
        run: scripts/libraw-bindings.ps1
        shell: pwsh
      - name: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: libraw-bindings-${{matrix.os}}
          path: |
            crates/libraw-sys/src/bindings-${{matrix.os}}.rs
          if-no-files-found: error
  commit:
      needs: libraw-bindings
      runs-on: ubuntu-slim
      steps:
        - uses: actions/checkout@v4
        - uses: actions/download-artifact@v4
          with:
            pattern: libraw-bindings-*
        - run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  
            git add crates/libraw-sys/src/
  
            if git diff --cached --quiet; then
              echo "No changes"
              exit 0
            fi
  
            git commit -m "Update libraw bindings"
            git push