name: libraw-bindgen
on:
  workflow_dispatch:

jobs:
  libraw-bindings:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: windows-latest
            os: win
          - machine: ubuntu-latest
            os: linux
          - machine: macos-latest
            os: macos
          - machine: ubuntu-24.04-arm
            os: linux-aarch64
    runs-on: ${{matrix.machine}}
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          run-install: false
      - uses: ./.github/actions/rust/setup-rust
      - name: libraw-bindings
        run: |
          scripts/libraw-bindings.ps1
        shell: pwsh

      - name: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: libraw-bindings-${{matrix.os}}
          path: |
            crates/libraw-sys/src/bindings-${{matrix.os}}.rs
          if-no-files-found: error
