name: libraw-bindgen
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  libraw-bindings:
    strategy:
      fail-fast: true
      matrix:
        include:
          - machine: windows-latest
            os: win
          - machine: ubuntu-latest
            os: linux
          - machine: macos-latest
            os: macos
          - machine: ubuntu-26.04-arm
            os: linux-aarch64
    runs-on: ${{matrix.machine}}
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - parallel:
          - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
            with:
              run-install: false
          - uses: ./.github/actions/rust/setup-rust
          - name: libraw-bindings
            run: scripts/libraw-bindings.ps1
            shell: pwsh
      - name: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add crates/libraw-sys/src/bindings-${{ matrix.os }}.rs
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update libraw bindings for ${{ matrix.os }}"
          git push --force-with-lease
        shell: bash
